services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3300:3000"   # Exponemos en 3300 porque 3000 ya est√° ocupado
    environment:
      - JAVA_TIMEZONE=America/Bogota
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=Micc1070004642*
      - MB_DB_HOST=172.17.0.1
    volumes:
      - ./metabase-data:/metabase-data
