project_name: sarupetrol_17_18


postgres_image_name: postgres:14
postgres_container_name: sarupetrol_17_18-container-postgres-14
postgres_volume_name: sarupetrol_17_18-volume-postgres-14
postgres_extra_settings:


odoo_rpc_timeout: 3600
odoo_host_xmlrpc_port: 9069
odoo_default_company:
  country_code: FR


odoo_versions:
  - 17.0
  - 18.0


odoo_version_settings:
  17.0:
  18.0:


migration_steps:
  - name: 1
    version: 17.0
    execution_context: regular
    complete_name: step_01__regular__17.0
    update: True

  - name: 2
    version: 18.0
    execution_context: openupgrade
    complete_name: step_02__openupgrade__18.0

  - name: 3
    version: 18.0
    execution_context: regular
    complete_name: step_03__regular__18.0
    update: True


workload_settings:

  # Ignored module list
  ignored_module_list: []

  # porting a module requires 45 minutes minimaly
  port_minimal_time: 45

  # a migration cost more for each version
  port_per_version: 15

  # Porting 120 lines of Python code costs 1 hour
  port_per_python_line_time: 0.5

  # Porting 120 lines of Javascript code costs 1 hour
  port_per_javascript_line_time: 0.5

  # Porting 10 lines of XML costs 1 minute
  port_per_xml_line_time: 0.10

  # Minimal time for Openupgrade PR
  open_upgrade_minimal_time: 10

  # time for a line of model in the openupgrade_analysis.txt
  openupgrade_model_line_time: 10

  # Time for a line of field in the openupgrade_analysis.txt
  openupgrade_field_line_time: 5

  # Time for a line of XML in the openupgrade_analysis.txt
  openupgrade_xml_line_time: 0.1
